"""add sales and sales_imports

Revision ID: 58380bcb59f2
Revises: 1a8487268027
Create Date: 2026-08-08 13:12:23.174402+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58380bcb59f2'
down_revision: str | None = '1a8487268027'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_imports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('accepted_row_count', sa.Integer(), nullable=True),
    sa.Column('rejected_row_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('processing', 'completed', 'failed')", name=op.f('ck_sales_imports_status_valid')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_sales_imports_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_imports')),
    sa.UniqueConstraint('location_id', 'content_hash', name=op.f('uq_sales_imports_location_id'))
    )
    op.create_index('ix_sales_imports_location_created', 'sales_imports', ['location_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sales_imports_location_id'), 'sales_imports', ['location_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('sales_import_id', sa.Uuid(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('item_name_normalized', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_sales_quantity_non_negative')),
    sa.CheckConstraint('revenue IS NULL OR revenue >= 0', name=op.f('ck_sales_revenue_non_negative')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_sales_location_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_import_id'], ['sales_imports.id'], name=op.f('fk_sales_sales_import_id_sales_imports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales')),
    sa.UniqueConstraint('location_id', 'business_date', 'item_name_normalized', name=op.f('uq_sales_location_id'))
    )
    op.create_index('ix_sales_location_business_date', 'sales', ['location_id', 'business_date'], unique=False)
    op.create_index('ix_sales_location_item_date', 'sales', ['location_id', 'item_name_normalized', 'business_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_location_item_date', table_name='sales')
    op.drop_index('ix_sales_location_business_date', table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_sales_imports_location_id'), table_name='sales_imports')
    op.drop_index('ix_sales_imports_location_created', table_name='sales_imports')
    op.drop_table('sales_imports')
    # ### end Alembic commands ###
