"""add recipes and ingredients

Revision ID: 6d174f81bafc
Revises: 7459ced28f0a
Create Date: 2026-08-09 15:28:30.934066+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d174f81bafc'
down_revision: str | None = '7459ced28f0a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_normalized', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_ingredients_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients')),
    sa.UniqueConstraint('location_id', 'name_normalized', name=op.f('uq_ingredients_location_id'))
    )
    op.create_index('ix_ingredients_location', 'ingredients', ['location_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('item_name_normalized', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_recipes_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    sa.UniqueConstraint('location_id', 'item_name_normalized', name=op.f('uq_recipes_location_id'))
    )
    op.create_index('ix_recipes_location', 'recipes', ['location_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_recipe_ingredients_amount_positive')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_recipe_ingredients_ingredient_id_ingredients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_ingredients_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredients')),
    sa.UniqueConstraint('recipe_id', 'ingredient_id', name=op.f('uq_recipe_ingredients_recipe_id'))
    )
    op.create_index('ix_recipe_ingredients_ingredient', 'recipe_ingredients', ['ingredient_id'], unique=False)
    op.create_index('ix_recipe_ingredients_recipe', 'recipe_ingredients', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_ingredients_recipe', table_name='recipe_ingredients')
    op.drop_index('ix_recipe_ingredients_ingredient', table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index('ix_recipes_location', table_name='recipes')
    op.drop_table('recipes')
    op.drop_index('ix_ingredients_location', table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
