"""add forecast model_name

Revision ID: 7459ced28f0a
Revises: f0c974485588
Create Date: 2026-08-08 22:14:14.968104+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7459ced28f0a'
down_revision: str | None = 'f0c974485588'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts', sa.Column('model_name', sa.Text(), server_default='weekday_average_v1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecasts', 'model_name')
    # ### end Alembic commands ###
