"""add forecast_runs and forecasts

Revision ID: d1d8601febef
Revises: 58380bcb59f2
Create Date: 2026-08-08 13:37:17.999503+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d8601febef'
down_revision: str | None = '58380bcb59f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('history_start_date', sa.Date(), nullable=True),
    sa.Column('history_end_date', sa.Date(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('horizon_days > 0', name=op.f('ck_forecast_runs_horizon_positive')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_forecast_runs_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_runs'))
    )
    op.create_index('ix_forecast_runs_location_generated', 'forecast_runs', ['location_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_forecast_runs_location_id'), 'forecast_runs', ['location_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('forecast_run_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('item_name_normalized', sa.Text(), nullable=False),
    sa.Column('predicted_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('predicted_quantity >= 0', name=op.f('ck_forecasts_predicted_quantity_non_negative')),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], name=op.f('fk_forecasts_forecast_run_id_forecast_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_forecasts_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecasts')),
    sa.UniqueConstraint('forecast_run_id', 'forecast_date', 'item_name_normalized', name=op.f('uq_forecasts_forecast_run_id'))
    )
    op.create_index('ix_forecasts_location_date', 'forecasts', ['location_id', 'forecast_date'], unique=False)
    op.create_index('ix_forecasts_location_item_date', 'forecasts', ['location_id', 'item_name_normalized', 'forecast_date'], unique=False)
    op.create_index('ix_forecasts_run', 'forecasts', ['forecast_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forecasts_run', table_name='forecasts')
    op.drop_index('ix_forecasts_location_item_date', table_name='forecasts')
    op.drop_index('ix_forecasts_location_date', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_forecast_runs_location_id'), table_name='forecast_runs')
    op.drop_index('ix_forecast_runs_location_generated', table_name='forecast_runs')
    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
