"""add mase and window win rate

Revision ID: f0c974485588
Revises: a6bd05673d76
Create Date: 2026-08-08 16:46:16.799638+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c974485588'
down_revision: str | None = 'a6bd05673d76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_evaluation_results', sa.Column('mase', sa.Numeric(precision=14, scale=6), nullable=True))
    op.add_column('model_evaluation_runs', sa.Column('window_win_rate', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('model_evaluation_windows', sa.Column('mase', sa.Numeric(precision=14, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_evaluation_windows', 'mase')
    op.drop_column('model_evaluation_runs', 'window_win_rate')
    op.drop_column('model_evaluation_results', 'mase')
    # ### end Alembic commands ###
