/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/restaurants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Restaurants */
        get: operations["list_restaurants_api_restaurants_get"];
        put?: never;
        /** Create Restaurant */
        post: operations["create_restaurant_api_restaurants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/restaurants/{restaurant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Restaurant */
        get: operations["get_restaurant_api_restaurants__restaurant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/restaurants/{restaurant_id}/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_restaurants__restaurant_id__locations_get"];
        put?: never;
        /** Create Location */
        post: operations["create_location_api_restaurants__restaurant_id__locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Location */
        get: operations["get_location_api_locations__location_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/sales/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sales Imports */
        get: operations["list_sales_imports_api_locations__location_id__sales_imports_get"];
        put?: never;
        /** Upload Sales Csv */
        post: operations["upload_sales_csv_api_locations__location_id__sales_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sales */
        get: operations["list_sales_api_locations__location_id__sales_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/sales/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sales Summary */
        get: operations["sales_summary_api_locations__location_id__sales_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/sales/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sales Daily */
        get: operations["sales_daily_api_locations__location_id__sales_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/forecasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Forecast */
        post: operations["generate_forecast_api_locations__location_id__forecasts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/forecasts/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Forecast */
        get: operations["latest_forecast_api_locations__location_id__forecasts_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/forecast-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Forecast Runs */
        get: operations["list_forecast_runs_api_locations__location_id__forecast_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast-runs/{forecast_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast Run */
        get: operations["get_forecast_run_api_forecast_runs__forecast_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/forecast-accuracy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast Accuracy */
        get: operations["forecast_accuracy_api_locations__location_id__forecast_accuracy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/forecast-backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast Backtest */
        get: operations["forecast_backtest_api_locations__location_id__forecast_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/model-evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Model Evaluation */
        post: operations["run_model_evaluation_api_locations__location_id__model_evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/model-evaluations/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Model Evaluation */
        get: operations["latest_model_evaluation_api_locations__location_id__model_evaluations_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/model-evaluations/by-item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Evaluation By Item */
        get: operations["model_evaluation_by_item_api_locations__location_id__model_evaluations_by_item_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/menu-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Menu Items */
        get: operations["list_menu_items_api_locations__location_id__menu_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingredients */
        get: operations["list_ingredients_api_locations__location_id__ingredients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/recipes/{item_name_normalized}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recipe */
        get: operations["get_recipe_api_locations__location_id__recipes__item_name_normalized__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Recipe */
        post: operations["create_recipe_api_locations__location_id__recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Recipe */
        put: operations["update_recipe_api_locations__location_id__recipes__recipe_id__put"];
        post?: never;
        /** Delete Recipe */
        delete: operations["delete_recipe_api_locations__location_id__recipes__recipe_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location_id}/ingredient-demand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingredient Demand */
        get: operations["ingredient_demand_api_locations__location_id__ingredient_demand_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestResponse */
        BacktestResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Window Days */
            window_days: number;
            /** Evaluated Observations */
            evaluated_observations: number;
            /** Wape */
            wape: string | null;
            /** Mae */
            mae: string | null;
            /** Bias */
            bias: string | null;
        };
        /** Body_upload_sales_csv_api_locations__location_id__sales_imports_post */
        Body_upload_sales_csv_api_locations__location_id__sales_imports_post: {
            /** File */
            file: string;
        };
        /** ForecastAccuracyResponse */
        ForecastAccuracyResponse: {
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Evaluated Observations */
            evaluated_observations: number;
            /** Wape */
            wape: string | null;
            /** Mae */
            mae: string | null;
            /** Bias */
            bias: string | null;
        };
        /** ForecastDay */
        ForecastDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Items */
            items: components["schemas"]["ForecastDayItem"][];
        };
        /** ForecastDayItem */
        ForecastDayItem: {
            /** Item Name */
            item_name: string;
            /** Predicted Quantity */
            predicted_quantity: string;
            /** Estimated Revenue */
            estimated_revenue: string | null;
            /** Model Name */
            model_name: string;
        };
        /** ForecastPointSchema */
        ForecastPointSchema: {
            /**
             * Forecast Date
             * Format: date
             */
            forecast_date: string;
            /** Item Name */
            item_name: string;
            /** Predicted Quantity */
            predicted_quantity: string;
            /** Model Name */
            model_name: string;
        };
        /** ForecastRunListResponse */
        ForecastRunListResponse: {
            /** Items */
            items: components["schemas"]["ForecastRunSchema"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ForecastRunSchema */
        ForecastRunSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Model Version */
            model_version: string;
            /** History Start Date */
            history_start_date: string | null;
            /** History End Date */
            history_end_date: string | null;
            /** Horizon Days */
            horizon_days: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** GenerateForecastResponse */
        GenerateForecastResponse: {
            run: components["schemas"]["ForecastRunSchema"];
            /** Forecasts */
            forecasts: components["schemas"]["ForecastPointSchema"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngredientDemandCoverage */
        IngredientDemandCoverage: {
            /** Total Items */
            total_items: number;
            /** Mapped Items */
            mapped_items: number;
            /** Unmapped Items */
            unmapped_items: string[];
        };
        /** IngredientDemandDay */
        IngredientDemandDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Ingredients */
            ingredients: components["schemas"]["IngredientQuantitySchema"][];
        };
        /** IngredientDemandResponse */
        IngredientDemandResponse: {
            /** Generated At */
            generated_at: string | null;
            /** Per Day */
            per_day: components["schemas"]["IngredientDemandDay"][];
            /** Totals */
            totals: components["schemas"]["IngredientQuantitySchema"][];
            coverage: components["schemas"]["IngredientDemandCoverage"];
        };
        /** IngredientListResponse */
        IngredientListResponse: {
            /** Items */
            items: components["schemas"]["IngredientResponse"][];
        };
        /** IngredientQuantitySchema */
        IngredientQuantitySchema: {
            /**
             * Ingredient Id
             * Format: uuid
             */
            ingredient_id: string;
            /** Name */
            name: string;
            /** Unit */
            unit: string;
            /** Quantity */
            quantity: string;
        };
        /** IngredientResponse */
        IngredientResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Unit */
            unit: string;
        };
        /** ItemChampionSchema */
        ItemChampionSchema: {
            /** Item Name */
            item_name: string;
            /** Selected Model */
            selected_model: string;
            /** Is Override */
            is_override: boolean;
            /** Reason */
            reason: string;
            /** Models */
            models: components["schemas"]["ModelEvaluationSchema"][];
        };
        /** LatestForecastResponse */
        LatestForecastResponse: {
            run: components["schemas"]["ForecastRunSchema"];
            /** Days */
            days: components["schemas"]["ForecastDay"][];
        };
        /** LocationCreate */
        LocationCreate: {
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
        };
        /** LocationListResponse */
        LocationListResponse: {
            /** Items */
            items: components["schemas"]["LocationResponse"][];
        };
        /** LocationResponse */
        LocationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Restaurant Id
             * Format: uuid
             */
            restaurant_id: string;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MenuItem */
        MenuItem: {
            /** Item Name */
            item_name: string;
            /** Item Name Normalized */
            item_name_normalized: string;
            /** Has Recipe */
            has_recipe: boolean;
        };
        /** MenuItemListResponse */
        MenuItemListResponse: {
            /** Items */
            items: components["schemas"]["MenuItem"][];
        };
        /** ModelEvaluationRunResponse */
        ModelEvaluationRunResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Horizon Days */
            horizon_days: number;
            /** Min Training Days */
            min_training_days: number;
            /** Window Step Days */
            window_step_days: number;
            /** Window Count */
            window_count: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Models */
            models: components["schemas"]["ModelEvaluationSchema"][];
            selection: components["schemas"]["ModelSelectionSchema"];
        };
        /** ModelEvaluationSchema */
        ModelEvaluationSchema: {
            /** Model Name */
            model_name: string;
            /** Is Baseline */
            is_baseline: boolean;
            /** Is Selected */
            is_selected: boolean;
            /** Evaluated Observations */
            evaluated_observations: number;
            /** Wape */
            wape: string | null;
            /** Mae */
            mae: string | null;
            /** Rmse */
            rmse: string | null;
            /** Bias */
            bias: string | null;
            /** Bias Pct */
            bias_pct: string | null;
            /** Mase */
            mase: string | null;
        };
        /** ModelSelectionSchema */
        ModelSelectionSchema: {
            /** Baseline Model */
            baseline_model: string;
            /** Challenger Model */
            challenger_model: string | null;
            /** Selected Model */
            selected_model: string;
            /** Relative Wape Improvement */
            relative_wape_improvement: string | null;
            /** Window Win Rate */
            window_win_rate: string | null;
            /** Reason */
            reason: string;
        };
        /** PerItemEvaluationResponse */
        PerItemEvaluationResponse: {
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Horizon Days */
            horizon_days: number;
            /** Global Champion */
            global_champion: string;
            /** Items */
            items: components["schemas"]["ItemChampionSchema"][];
        };
        /** RecipeCreate */
        RecipeCreate: {
            /** Item Name */
            item_name: string;
            /** Lines */
            lines: components["schemas"]["RecipeLineInput"][];
        };
        /**
         * RecipeLineInput
         * @description One ingredient line. Either reference an existing ingredient by id, or
         *     supply a new ingredient name + unit to be created inline.
         */
        RecipeLineInput: {
            /** Ingredient Id */
            ingredient_id?: string | null;
            /** Ingredient Name */
            ingredient_name?: string | null;
            /** Unit */
            unit?: string | null;
            /** Amount */
            amount: number | string;
        };
        /** RecipeLineResponse */
        RecipeLineResponse: {
            /**
             * Ingredient Id
             * Format: uuid
             */
            ingredient_id: string;
            /** Ingredient Name */
            ingredient_name: string;
            /** Unit */
            unit: string;
            /** Amount */
            amount: string;
        };
        /** RecipeResponse */
        RecipeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Item Name */
            item_name: string;
            /** Item Name Normalized */
            item_name_normalized: string;
            /** Lines */
            lines: components["schemas"]["RecipeLineResponse"][];
        };
        /** RecipeUpdate */
        RecipeUpdate: {
            /** Lines */
            lines: components["schemas"]["RecipeLineInput"][];
        };
        /** RestaurantCreate */
        RestaurantCreate: {
            /** Name */
            name: string;
        };
        /** RestaurantListResponse */
        RestaurantListResponse: {
            /** Items */
            items: components["schemas"]["RestaurantResponse"][];
        };
        /** RestaurantResponse */
        RestaurantResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "member";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SaleResponse */
        SaleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Business Date
             * Format: date
             */
            business_date: string;
            /** Item Name */
            item_name: string;
            /** Quantity */
            quantity: number;
            /** Revenue */
            revenue: string | null;
        };
        /** SalesDailyPoint */
        SalesDailyPoint: {
            /**
             * Business Date
             * Format: date
             */
            business_date: string;
            /** Total Quantity */
            total_quantity: number;
            /** Total Revenue */
            total_revenue: string | null;
        };
        /** SalesDailyResponse */
        SalesDailyResponse: {
            /** Items */
            items: components["schemas"]["SalesDailyPoint"][];
        };
        /** SalesImportListItem */
        SalesImportListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** Status */
            status: string;
            /** Row Count */
            row_count: number | null;
            /** Accepted Row Count */
            accepted_row_count: number | null;
            /** Rejected Row Count */
            rejected_row_count: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /** SalesImportListResponse */
        SalesImportListResponse: {
            /** Items */
            items: components["schemas"]["SalesImportListItem"][];
        };
        /** SalesImportResponse */
        SalesImportResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Original Filename */
            original_filename: string;
            /** Status */
            status: string;
            /** Row Count */
            row_count: number | null;
            /** Accepted Row Count */
            accepted_row_count: number | null;
            /** Rejected Row Count */
            rejected_row_count: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Forecast Generated */
            forecast_generated: boolean;
        };
        /** SalesListResponse */
        SalesListResponse: {
            /** Items */
            items: components["schemas"]["SaleResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SalesSummaryResponse */
        SalesSummaryResponse: {
            /** Start Date */
            start_date: string | null;
            /** End Date */
            end_date: string | null;
            /** Total Quantity */
            total_quantity: number;
            /** Total Revenue */
            total_revenue: string | null;
            /** Days With Data */
            days_with_data: number;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_restaurants_api_restaurants_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_restaurant_api_restaurants_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestaurantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_restaurant_api_restaurants__restaurant_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_locations_api_restaurants__restaurant_id__locations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_location_api_restaurants__restaurant_id__locations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                restaurant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_location_api_locations__location_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sales_imports_api_locations__location_id__sales_imports_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesImportListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_sales_csv_api_locations__location_id__sales_imports_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_sales_csv_api_locations__location_id__sales_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sales_api_locations__location_id__sales_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                item?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sales_summary_api_locations__location_id__sales_summary_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sales_daily_api_locations__location_id__sales_daily_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesDailyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_forecast_api_locations__location_id__forecasts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_forecast_api_locations__location_id__forecasts_latest_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_forecast_runs_api_locations__location_id__forecast_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_run_api_forecast_runs__forecast_run_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                forecast_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_accuracy_api_locations__location_id__forecast_accuracy_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                item?: string | null;
                forecast_run_id?: string | null;
            };
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastAccuracyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_backtest_api_locations__location_id__forecast_backtest_get: {
        parameters: {
            query?: {
                window_days?: number;
            };
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_model_evaluation_api_locations__location_id__model_evaluations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelEvaluationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_model_evaluation_api_locations__location_id__model_evaluations_latest_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelEvaluationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_evaluation_by_item_api_locations__location_id__model_evaluations_by_item_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerItemEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_menu_items_api_locations__location_id__menu_items_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItemListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingredients_api_locations__location_id__ingredients_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_api_locations__location_id__recipes__item_name_normalized__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
                item_name_normalized: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recipe_api_locations__location_id__recipes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_recipe_api_locations__location_id__recipes__recipe_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recipe_api_locations__location_id__recipes__recipe_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingredient_demand_api_locations__location_id__ingredient_demand_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "x-dev-subject"?: string | null;
            };
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientDemandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
